## Logistic Regression

In [73]:
import pandas as pd
import numpy as np

In [74]:
data_preprocessed = pd.read_csv('F:/DATA SCIENCE/Absenteeism_preprocessed.csv')

In [75]:
data_preprocessed

reason_0  reason_1  reason_2  reason_3  Transportation Expense  \
0           0         0         0         1                     289   
1           0         0         0         0                     118   
2           0         0         0         1                     179   
3           1         0         0         0                     279   
4           0         0         0         1                     289   
..        ...       ...       ...       ...                     ...   
695         1         0         0         0                     179   
696         1         0         0         0                     225   
697         1         0         0         0                     330   
698         0         0         0         1                     235   
699         0         0         0         1                     291   

     Distance to Work  Age  Daily Work Load Average  Body Mass Index  \
0                  36   33                  239.554               30   
1                  13   50                  239.554               31   
2                  51   38                  239.554               31   
3                   5   39                  239.554               24   
4                  36   33                  239.554               30   
..                ...  ...                      ...              ...   
695                22   40                  237.656               22   
696                26   28                  237.656               24   
697                16   28                  237.656               25   
698                16   32                  237.656               25   
699                31   40                  237.656               25   

     Education  Children  Pets  Absenteeism Time in Hours  Month  Day  
0          1.0         2     1                          4      7    1  
1          1.0         1     0                          0      7    1  
2          1.0         0     0                          2      7    2  
3          1.0         2     0                          4      7    3  
4          1.0         2     1                          2      7    3  
..         ...       ...   ...                        ...    ...  ...  
695        1.0         2     0                          8      5    2  
696        1.0         1     2                          3      5    2  
697        1.0         0     0                          8      5    3  
698        NaN         0     0                          2      5    3  
699        1.0         1     1                          2      5    3  

[700 rows x 15 columns]

In [76]:
data_preprocessed = data_preprocessed.dropna()

In [77]:
data_preprocessed.isnull().sum()

reason_0                     0
reason_1                     0
reason_2                     0
reason_3                     0
Transportation Expense       0
Distance to Work             0
Age                          0
Daily Work Load Average      0
Body Mass Index              0
Education                    0
Children                     0
Pets                         0
Absenteeism Time in Hours    0
Month                        0
Day                          0
dtype: int64

In [78]:
data_preprocessed

reason_0  reason_1  reason_2  reason_3  Transportation Expense  \
0           0         0         0         1                     289   
1           0         0         0         0                     118   
2           0         0         0         1                     179   
3           1         0         0         0                     279   
4           0         0         0         1                     289   
..        ...       ...       ...       ...                     ...   
694         0         0         0         1                     291   
695         1         0         0         0                     179   
696         1         0         0         0                     225   
697         1         0         0         0                     330   
699         0         0         0         1                     291   

     Distance to Work  Age  Daily Work Load Average  Body Mass Index  \
0                  36   33                  239.554               30   
1                  13   50                  239.554               31   
2                  51   38                  239.554               31   
3                   5   39                  239.554               24   
4                  36   33                  239.554               30   
..                ...  ...                      ...              ...   
694                31   40                  237.656               25   
695                22   40                  237.656               22   
696                26   28                  237.656               24   
697                16   28                  237.656               25   
699                31   40                  237.656               25   

     Education  Children  Pets  Absenteeism Time in Hours  Month  Day  
0          1.0         2     1                          4      7    1  
1          1.0         1     0                          0      7    1  
2          1.0         0     0                          2      7    2  
3          1.0         2     0                          4      7    3  
4          1.0         2     1                          2      7    3  
..         ...       ...   ...                        ...    ...  ...  
694        1.0         1     1                          8      5    2  
695        1.0         2     0                          8      5    2  
696        1.0         1     2                          3      5    2  
697        1.0         0     0                          8      5    3  
699        1.0         1     1                          2      5    3  

[627 rows x 15 columns]

In [80]:
#data_preprocessed.drop([698],axis = 0)

## Create the targets

In [81]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [82]:
# if median is <= 3 then it is moderately absent and >= 4 then it is excessively absent.

In [83]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours']> 3,1,0)

In [84]:
"""targets = np.where(data_preprocessed['Absenteeism Time in Hours']>
                       data_preprocessed['Absenteeism Time in Hours'].median(),1,0)"""
#this is best method to find targets

SyntaxError: EOF while scanning triple-quoted string literal (<ipython-input-84-e0f152943ac8>, line 3)

In [86]:
targets.shape

(627,)

In [87]:
data_preprocessed['Excessive absenteeism'] = targets
data_preprocessed

<ipython-input-87-e73299965e0a>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_preprocessed['Excessive absenteeism'] = targets


reason_0  reason_1  reason_2  reason_3  Transportation Expense  \
0           0         0         0         1                     289   
1           0         0         0         0                     118   
2           0         0         0         1                     179   
3           1         0         0         0                     279   
4           0         0         0         1                     289   
..        ...       ...       ...       ...                     ...   
694         0         0         0         1                     291   
695         1         0         0         0                     179   
696         1         0         0         0                     225   
697         1         0         0         0                     330   
699         0         0         0         1                     291   

     Distance to Work  Age  Daily Work Load Average  Body Mass Index  \
0                  36   33                  239.554               30   
1                  13   50                  239.554               31   
2                  51   38                  239.554               31   
3                   5   39                  239.554               24   
4                  36   33                  239.554               30   
..                ...  ...                      ...              ...   
694                31   40                  237.656               25   
695                22   40                  237.656               22   
696                26   28                  237.656               24   
697                16   28                  237.656               25   
699                31   40                  237.656               25   

     Education  Children  Pets  Absenteeism Time in Hours  Month  Day  \
0          1.0         2     1                          4      7    1   
1          1.0         1     0                          0      7    1   
2          1.0         0     0                          2      7    2   
3          1.0         2     0                          4      7    3   
4          1.0         2     1                          2      7    3   
..         ...       ...   ...                        ...    ...  ...   
694        1.0         1     1                          8      5    2   
695        1.0         2     0                          8      5    2   
696        1.0         1     2                          3      5    2   
697        1.0         0     0                          8      5    3   
699        1.0         1     1                          2      5    3   

     Excessive absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
694                      1  
695                      1  
696                      0  
697                      1  
699                      0  

[627 rows x 16 columns]

In [89]:
targets.sum() / targets.shape[0]

0.4625199362041467

In [138]:
data_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day',
                                       'Distance to Work','Daily Work Load Average'], axis = 1)

In [139]:
data_targets is data_preprocessed

False

## Select the inputs for the Regression

In [140]:
data_targets.shape

(627, 12)

In [141]:
data_targets.iloc[:,0:11]
# Remove the column Excessive absenteeism
# data_taregts.iloc[:,:-1]

reason_0  reason_1  reason_2  reason_3  Transportation Expense  Age  \
0           0         0         0         1                     289   33   
1           0         0         0         0                     118   50   
2           0         0         0         1                     179   38   
3           1         0         0         0                     279   39   
4           0         0         0         1                     289   33   
..        ...       ...       ...       ...                     ...  ...   
694         0         0         0         1                     291   40   
695         1         0         0         0                     179   40   
696         1         0         0         0                     225   28   
697         1         0         0         0                     330   28   
699         0         0         0         1                     291   40   

     Body Mass Index  Education  Children  Pets  Month  
0                 30        1.0         2     1      7  
1                 31        1.0         1     0      7  
2                 31        1.0         0     0      7  
3                 24        1.0         2     0      7  
4                 30        1.0         2     1      7  
..               ...        ...       ...   ...    ...  
694               25        1.0         1     1      5  
695               22        1.0         2     0      5  
696               24        1.0         1     2      5  
697               25        1.0         0     0      5  
699               25        1.0         1     1      5  

[627 rows x 11 columns]

In [142]:
unscaled_inputs = data_targets.iloc[:,0:11]

In [143]:
unscaled_inputs

reason_0  reason_1  reason_2  reason_3  Transportation Expense  Age  \
0           0         0         0         1                     289   33   
1           0         0         0         0                     118   50   
2           0         0         0         1                     179   38   
3           1         0         0         0                     279   39   
4           0         0         0         1                     289   33   
..        ...       ...       ...       ...                     ...  ...   
694         0         0         0         1                     291   40   
695         1         0         0         0                     179   40   
696         1         0         0         0                     225   28   
697         1         0         0         0                     330   28   
699         0         0         0         1                     291   40   

     Body Mass Index  Education  Children  Pets  Month  
0                 30        1.0         2     1      7  
1                 31        1.0         1     0      7  
2                 31        1.0         0     0      7  
3                 24        1.0         2     0      7  
4                 30        1.0         2     1      7  
..               ...        ...       ...   ...    ...  
694               25        1.0         1     1      5  
695               22        1.0         2     0      5  
696               24        1.0         1     2      5  
697               25        1.0         0     0      5  
699               25        1.0         1     1      5  

[627 rows x 11 columns]

## Standardize the data 

In [144]:
from sklearn.preprocessing import StandardScaler

In [187]:
absenteeism_scaler = StandardScaler()

In [146]:
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler()

In [147]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [148]:
scaled_inputs.shape

(627, 11)

In [149]:
scaled_inputs   

array([[-0.56322899, -0.08965816, -0.31622777, ...,  0.78863884,
         0.22084015,  0.01771079],
       [-0.56322899, -0.08965816, -0.31622777, ..., -0.09278104,
        -0.60336684,  0.01771079],
       [-0.56322899, -0.08965816, -0.31622777, ..., -0.97420092,
        -0.60336684,  0.01771079],
       ...,
       [ 1.7754768 , -0.08965816, -0.31622777, ..., -0.09278104,
         1.04504715, -0.58254129],
       [ 1.7754768 , -0.08965816, -0.31622777, ..., -0.97420092,
        -0.60336684, -0.58254129],
       [-0.56322899, -0.08965816, -0.31622777, ..., -0.09278104,
         0.22084015, -0.58254129]])

## Split the Data

In [151]:
from sklearn.model_selection import train_test_split

In [152]:
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,targets,random_state = 20)

In [153]:
x_train.shape

(470, 11)

In [154]:
x_test.shape

(157, 11)

## Training the model

In [155]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [183]:
reg = LogisticRegression()

In [184]:
reg.fit(x_train,y_train)

LogisticRegression()

In [159]:
reg.score(x_train,y_train)

0.7829787234042553

## Manually check the Accuracy

In [160]:
model_outputs = reg.predict(x_train)
model_outputs

array([1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,

In [161]:
y_train

array([1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,

In [162]:
y_train is model_outputs   # y_train == model_outputs

False

In [163]:
np.sum(y_train == model_outputs)

368

In [164]:
model_outputs.shape 

(470,)

In [165]:
acc = np.sum(y_train == model_outputs) / model_outputs.shape[0]
# it gives accuracy same as before.
acc

0.7829787234042553

## Finding the coefficient and accuracy

In [166]:
reg.intercept_

array([-0.20462281])

In [167]:
reg.coef_

array([[ 1.9556981 ,  0.58056953,  1.47951327,  1.17289328,  0.66369785,
        -0.29539939,  0.1439739 ,  0.        ,  0.35080627, -0.42949319,
        -0.10898065]])

In [168]:
scaled_inputs.columns.values
# this gives error,bcoz sklearn compatible with dataframe and ndarray also while using ML.

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

In [169]:
feature_name = unscaled_inputs.columns.values

In [170]:
summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_name)

summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table

Feature name  Coefficient
0                 reason_0     1.955698
1                 reason_1     0.580570
2                 reason_2     1.479513
3                 reason_3     1.172893
4   Transportation Expense     0.663698
5                      Age    -0.295399
6          Body Mass Index     0.143974
7                Education     0.000000
8                 Children     0.350806
9                     Pets    -0.429493
10                   Month    -0.108981

In [171]:
summary_table.index = summary_table.index + 1   # blank the 0th index
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -0.204623
1                 reason_0     1.955698
2                 reason_1     0.580570
3                 reason_2     1.479513
4                 reason_3     1.172893
5   Transportation Expense     0.663698
6                      Age    -0.295399
7          Body Mass Index     0.143974
8                Education     0.000000
9                 Children     0.350806
10                    Pets    -0.429493
11                   Month    -0.108981

## Interpreting the coefficients

In [172]:
summary_table['odd_ratio'] = np.exp(summary_table.Coefficient)  # exponantial of coefficient.
summary_table.sort_values('odd_ratio',ascending  = False)

Feature name  Coefficient  odd_ratio
1                 reason_0     1.955698   7.068852
3                 reason_2     1.479513   4.390808
4                 reason_3     1.172893   3.231328
5   Transportation Expense     0.663698   1.941960
2                 reason_1     0.580570   1.787056
9                 Children     0.350806   1.420212
7          Body Mass Index     0.143974   1.154854
8                Education     0.000000   1.000000
11                   Month    -0.108981   0.896748
0                Intercept    -0.204623   0.814955
6                      Age    -0.295399   0.744234
10                    Pets    -0.429493   0.650839

In [173]:
# If coefficient value is far away to 0 and odd ratio is near to 1 then it is important.

In [174]:
# reason for absence and transportation expense,children and daily work load is mostly affect on the result.
# reason 0 is various diseases, 1 for pregency and giving birth, 2 for poising and 3 for light diseases.

In [175]:
# Backward Elimination = if P-value > 0.05 then it should be removed.
# But in sklearn, if the value of weights is low then we can remove it.

In [176]:
# go to the checkpoint where we created targets. And remove the features that should not affect our result.

## Testing the Data

In [179]:
reg.score(x_test,y_test)  # test accuracy is always less than the train accuracy.

0.7388535031847133

In [181]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.47701269, 0.52298731],
       [0.78685507, 0.21314493],
       [0.23451891, 0.76548109],
       [0.71707082, 0.28292918],
       [0.58730746, 0.41269254],
       [0.80284881, 0.19715119],
       [0.75814423, 0.24185577],
       [0.41318167, 0.58681833],
       [0.47324548, 0.52675452],
       [0.23451891, 0.76548109],
       [0.25154751, 0.74845249],
       [0.71038817, 0.28961183],
       [0.24242142, 0.75757858],
       [0.47143778, 0.52856222],
       [0.44522171, 0.55477829],
       [0.3749626 , 0.6250374 ],
       [0.18494659, 0.81505341],
       [0.71326935, 0.28673065],
       [0.779702  , 0.220298  ],
       [0.71038817, 0.28961183],
       [0.87604689, 0.12395311],
       [0.6490818 , 0.3509182 ],
       [0.73864011, 0.26135989],
       [0.87604689, 0.12395311],
       [0.19587549, 0.80412451],
       [0.47701269, 0.52298731],
       [0.13434887, 0.86565113],
       [0.18978365, 0.81021635],
       [0.52045713, 0.47954287],
       [0.26832802, 0.73167198],
       [0.

In [182]:
predicted_proba.shape

(157, 2)

## Save the Model

In [185]:
import pickle

In [186]:
with open('Model','wb') as file:
    pickle.dump(reg,file)

In [188]:
with open('scaler_file','wb') as file:
    pickle.dump(absenteeism_scaler,file)